### PR TITLE
Fix manifest.json issues

### PR DESCRIPTION
**Pull request by GTB3NW**
- set min engine version to 1.16.210 (1.14 does not support gametests afaik)
- lowercase the uuids (I just generated some new ones)
- adds comments to describe what the native modules are

### CODE REVIEW

**Review by mammerla — COMMENTED** [review]
Could we potentially avoid adding in the comments?  They are a good thing, but I'd worry that comments in JSON are not parseable everywhere (even if MC does fine with them)

**Comment by GTB3NW** [comment]
> Could we potentially avoid adding in the comments?

For sure, but I think it's worthwhile investigating if they should stay. It really depends on the intent of this repo, is it meant to be downloaded and used directly, or inspected visually?

> They are a good thing, but I'd worry that comments in JSON are not parseable everywhere (even if MC does fine with them)

Vscode one of the recommended editors for addons fully supports jsonc and even in regular json mode isn't too fussy. Could we instead add a workspace setting to default all json files to jsonc format?

**Comment by GTB3NW** [comment]
BTW, I am totally happy to remove it for now and create a new MR for this specific issue, that way we can get the rest of the changes in.

**Comment by mammerla** [comment]
Yep, VSCode's (default?) mode showing errors for JSON files is what I was thinking about.  Let's remove the comments for now just so that they are when opened up in plain VSCode.  If we have bigger projects we should include workspace settings to stop VSCode from complaining.  thanks!

**Comment by GTB3NW** [comment]
PR updated! :+1:

**Comment by mammerla** [comment]
Thanks!

**Pull request merged**
